select 
    CUSTOMER_ID,
    CUSTOMER_AGE,
    CUSTOMER_GENDER,
    CUSTOMER_INCOME,
    CUSTOMER_LOYALTY_LEVEL
from {{source("snowflake","walmart")}}
group by CUSTOMER_ID, CUSTOMER_AGE, CUSTOMER_GENDER, CUSTOMER_INCOME, CUSTOMER_LOYALTY_LEVEL